# dbt_project.yml

name: 'gainers'
version: '1.0.0'
config-version: 2   # <-- you were missing this line (important for dbt v1+)

profile: 'gainers'  # <-- this matches your project and is good

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Configure seeds (this is new!)
seeds:
  gainers:
    wsjgainers_norm20250406_215103:
      loaded_at_field: null
    ygainers_norm20250406_215048:
      loaded_at_field: null

# Configure models
models:
  gainers:
    +materialized: view
    example:
      +materialized: view
